name: Rollback Frontend

on:
  workflow_dispatch:

jobs:
  rollback:
    runs-on: ubuntu-latest

    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}

    steps:
      - name: Configure kubectl for OKE
        uses: oracle-actions/configure-kubectl-oke@v1.5.0
        with:
          cluster: ${{ secrets.OCI_CLUSTER_OCID }}

      - name: Rollback frontend
        run: |
          kubectl rollout undo deployment/mazetasks-frontend
          kubectl rollout status deployment/mazetasks-frontend
